// <auto-generated />
using System;
using DesafioWebAPI_03.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DesafioWebAPI_03.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210522193919_Migration02")]
    partial class Migration02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Responsavel", b =>
                {
                    b.Property<int>("IdResponsavel")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nome")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdResponsavel");

                    b.ToTable("Responsaveis");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Video", b =>
                {
                    b.Property<int>("IdVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdResponsavel")
                        .HasColumnType("int");

                    b.Property<int?>("IdadeMin")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("URL")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("IdVideo");

                    b.HasIndex("IdResponsavel");

                    b.ToTable("Videos");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.VideoCategoria", b =>
                {
                    b.Property<int>("IdVideoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdVideo")
                        .HasColumnType("int");

                    b.HasKey("IdVideoCategoria");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdVideo");

                    b.ToTable("VideoCategorias");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Video", b =>
                {
                    b.HasOne("DesafioWebAPI_03.Domain.Entity.Responsavel", "Responsavel")
                        .WithMany("Videos")
                        .HasForeignKey("IdResponsavel")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Responsavel");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.VideoCategoria", b =>
                {
                    b.HasOne("DesafioWebAPI_03.Domain.Entity.Categoria", "Categoria")
                        .WithMany("VideoCategorias")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DesafioWebAPI_03.Domain.Entity.Video", "Video")
                        .WithMany("VideoCategorias")
                        .HasForeignKey("IdVideo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Categoria", b =>
                {
                    b.Navigation("VideoCategorias");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Responsavel", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("DesafioWebAPI_03.Domain.Entity.Video", b =>
                {
                    b.Navigation("VideoCategorias");
                });
#pragma warning restore 612, 618
        }
    }
}
